dataset:
  json_data: ./data/yelp/yelp.json
  csv_data: ./data/yelp/yelp-schema.csv

max_len: 256


regsql_cnf:
  pretrained_bert_model: bert-base-uncased
  max_select_num: 5
  max_where_num: 10
  op_num: 6
  agg_num: 6
  drop_rate: 0.2
  start_end_hidden_size: 64

train_cnf:
  batch_size: 16
  epochs: 6
  warmup_rate: 0.1
  lr: 3e-5
  decay: 0.01
  verbose: true




